# -*- coding: utf-8 -*-
"""HTML_Quick_Styler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QQvsuplOtO0hzzdKlDh_2-jPngv5i5KM
"""

!pip install gradio
!pip install transformers
!pip install accelerate
!pip install torch

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_name = "ibm-granite/granite-3.3-2b-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto"
)

print("Model Loaded Successfully")

class ColorPaletteGenerator:
    def __init__(self):
        self.palettes = {
            "modern": {
                "primary": "#6366F1",
                "secondary": "#8B5CF6",
                "background": "#0F172A",
                "text": "#F8FAFC"
            },
            "ocean": {
                "primary": "#0284C7",
                "secondary": "#06B6D4",
                "background": "#0C4A6E",
                "text": "#E0F2FE"
            },
            "forest": {
                "primary": "#16A34A",
                "secondary": "#22C55E",
                "background": "#052E16",
                "text": "#DCFCE7"
            }
        }

    def get_palette(self, name):
        return self.palettes.get(name, self.palettes["modern"])

class HTMLPageBuilder:

    def build_page(self, title, description, colors):

        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
        <title>{title}</title>

        <style>
        body {{
            background:{colors['background']};
            color:{colors['text']};
            font-family:Arial;
        }}

        header {{
            background:{colors['primary']};
            padding:40px;
            text-align:center;
        }}

        section {{
            padding:40px;
        }}

        button {{
            background:{colors['secondary']};
            border:none;
            padding:10px 20px;
            color:white;
        }}
        </style>

        </head>

        <body>

        <header>
        <h1>{title}</h1>
        </header>

        <section>
        <p>{description}</p>
        <button>Learn More</button>
        </section>

        </body>
        </html>
        """

        return html

palette = ColorPaletteGenerator()
builder = HTMLPageBuilder()

def generate_page(title, description, style):

    colors = palette.get_palette(style)

    html = builder.build_page(title, description, colors)

    return html

import gradio as gr

with gr.Blocks() as demo:

    gr.Markdown("# HTML Quick Styler")

    title = gr.Textbox(label="Page Title")
    desc = gr.Textbox(label="Description")

    style = gr.Dropdown(
        ["modern","ocean","forest"],
        label="Color Style"
    )

    output = gr.Code(label="Generated HTML")

    btn = gr.Button("Generate Page")

    btn.click(
        generate_page,
        inputs=[title,desc,style],
        outputs=output
    )

demo.launch(share=True)

